name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        working-directory: apps/docs
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Build Storybook
        working-directory: apps/docs
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Verify build output
        working-directory: apps/docs
        run: |
          ls -la storybook-static
          [ -f storybook-static/index.html ] || exit 1

      - name: Deploy to GitHub Pages (fallback)
        if: always() 
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/docs/storybook-static
          destination_dir: ./ 
