name: Deploy Storybook

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Важно для работы gh-pages

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git remote set-url origin https://github.com/${{ github.repository }}.git
                  git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)"

            - name: Build Storybook
              working-directory: apps/docs
              run: yarn build-storybook

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: apps/docs/storybook-static
                  keep_files: false # Очищать перед деплоем
