name: Deploy Storybook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Добавлен таймаут

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Более точное указание версии
          cache: 'yarn'

      - name: Install dependencies
        working-directory: apps/docs
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)"

      - name: Build Storybook
        working-directory: apps/docs
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'  # Увеличение памяти для Node

      - name: Verify build output
        working-directory: apps/docs
        run: |
          ls -la storybook-static
          [ -f storybook-static/index.html ] || exit 1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/docs/storybook-static
          keep_files: false
          force_orphan: true  # Гарантирует чистый деплой
